import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'mr' | 'bn' | 'gu' | 'pa';

interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const languages: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

type TranslationKey = 
  | 'welcome'
  | 'login'
  | 'register'
  | 'email'
  | 'password'
  | 'name'
  | 'phone'
  | 'location'
  | 'cropType'
  | 'dashboard'
  | 'weather'
  | 'soilHealth'
  | 'pestDetection'
  | 'marketPrices'
  | 'chatbot'
  | 'profile'
  | 'logout'
  | 'askQuestion'
  | 'voiceInput'
  | 'uploadImage'
  | 'alerts'
  | 'recommendations'
  | 'temperature'
  | 'humidity'
  | 'rainfall'
  | 'windSpeed'
  | 'soilPH'
  | 'nitrogen'
  | 'phosphorus'
  | 'potassium'
  | 'moisture'
  | 'analyze'
  | 'loading'
  | 'submit'
  | 'cancel'
  | 'save'
  | 'selectLanguage'
  | 'greeting'
  | 'howCanIHelp'
  | 'todayWeather'
  | 'marketUpdate'
  | 'farmerLogin'
  | 'adminLogin'
  | 'newFarmer'
  | 'existingUser'
  | 'welcomeBack'
  | 'createAccount'
  | 'loginDescription'
  | 'registerDescription'
  | 'fullName'
  | 'enterName'
  | 'enterLocation'
  | 'preferredLanguage'
  | 'enterCrops'
  | 'signIn'
  | 'signUp'
  | 'noAccount'
  | 'hasAccount'
  | 'pleaseWait'
  | 'loginSuccess'
  | 'accountCreated'
  | 'error'
  | 'loginError'
  | 'registrationSuccess'
  | 'registrationError'
  | 'demoCredentials'
  | 'fetchingWeather'
  | 'retry'
  | 'forecast'
  | 'farmingRecommendations'
  | 'gettingRecommendations'
  | 'noRecommendations'
  | 'failedToGetRecommendations'
  | 'logoutSuccess'
  | 'logoutMessage';

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    welcome: 'Welcome to Kisan Mitra',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    phone: 'Phone Number',
    location: 'Location',
    cropType: 'Crop Type',
    dashboard: 'Dashboard',
    weather: 'Weather',
    soilHealth: 'Soil Health',
    pestDetection: 'Pest Detection',
    marketPrices: 'Market Prices',
    chatbot: 'Ask Kisan Mitra',
    profile: 'Profile',
    logout: 'Logout',
    askQuestion: 'Ask your question...',
    voiceInput: 'Tap to speak',
    uploadImage: 'Upload Image',
    alerts: 'Alerts',
    recommendations: 'Recommendations',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    windSpeed: 'Wind Speed',
    soilPH: 'Soil pH',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    moisture: 'Moisture',
    analyze: 'Analyze',
    loading: 'Loading...',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    selectLanguage: 'Select Language',
    greeting: 'Namaste',
    howCanIHelp: 'How can I help you today?',
    todayWeather: "Today's Weather",
    marketUpdate: 'Market Update',
    farmerLogin: 'Farmer Login',
    adminLogin: 'Admin Login',
    newFarmer: 'New Farmer? Register',
    existingUser: 'Already have an account? Login',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    loginDescription: 'Sign in to access your crop advisory',
    registerDescription: 'Join Krishi Mitra for smart farming',
    fullName: 'Full Name',
    enterName: 'Enter your name',
    enterLocation: 'Your village/city, State',
    preferredLanguage: 'Preferred Language',
    enterCrops: 'Rice, Wheat, Sugarcane...',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    pleaseWait: 'Please wait...',
    loginSuccess: 'Login Successful',
    accountCreated: 'Your account has been created!',
    error: 'Error',
    loginError: 'Invalid email or password',
    registrationSuccess: 'Registration Successful',
    registrationError: 'Registration failed. Please try again.',
    demoCredentials: 'Demo Credentials:',
    fetchingWeather: 'Fetching weather data...',
    retry: 'Retry',
    forecast: '5-Day Forecast',
    farmingRecommendations: 'AI Farming Recommendations',
    gettingRecommendations: 'Getting recommendations...',
    noRecommendations: 'No recommendations available',
    failedToGetRecommendations: 'Failed to get farming recommendations',
    logoutSuccess: 'Logged Out',
    logoutMessage: 'You have been logged out successfully.',
  },
  hi: {
    welcome: 'किसान मित्र में आपका स्वागत है',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूरा नाम',
    phone: 'फोन नंबर',
    location: 'स्थान',
    cropType: 'फसल का प्रकार',
    dashboard: 'डैशबोर्ड',
    weather: 'मौसम',
    soilHealth: 'मिट्टी की सेहत',
    pestDetection: 'कीट पहचान',
    marketPrices: 'बाजार भाव',
    chatbot: 'किसान मित्र से पूछें',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    askQuestion: 'अपना सवाल पूछें...',
    voiceInput: 'बोलने के लिए टैप करें',
    uploadImage: 'फोटो अपलोड करें',
    alerts: 'अलर्ट',
    recommendations: 'सिफारिशें',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'बारिश',
    windSpeed: 'हवा की गति',
    soilPH: 'मिट्टी का pH',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फॉस्फोरस (P)',
    potassium: 'पोटाश (K)',
    moisture: 'नमी',
    analyze: 'विश्लेषण करें',
    loading: 'लोड हो रहा है...',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    selectLanguage: 'भाषा चुनें',
    greeting: 'नमस्ते',
    howCanIHelp: 'आज मैं आपकी कैसे मदद कर सकता हूं?',
    todayWeather: 'आज का मौसम',
    marketUpdate: 'बाजार अपडेट',
    farmerLogin: 'किसान लॉगिन',
    adminLogin: 'एडमिन लॉगिन',
    newFarmer: 'नए किसान? पंजीकरण करें',
    existingUser: 'पहले से खाता है? लॉगिन करें',
    welcomeBack: 'वापसी पर स्वागत',
    createAccount: 'खाता बनाएं',
    loginDescription: 'अपनी फसल सलाह तक पहुंचने के लिए साइन इन करें',
    registerDescription: 'स्मार्ट खेती के लिए कृषि मित्र से जुड़ें',
    fullName: 'पूरा नाम',
    enterName: 'अपना नाम दर्ज करें',
    enterLocation: 'आपका गांव/शहर, राज्य',
    preferredLanguage: 'पसंदीदा भाषा',
    enterCrops: 'चावल, गेहूं, गन्ना...',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    noAccount: 'खाता नहीं है?',
    hasAccount: 'पहले से खाता है?',
    pleaseWait: 'कृपया प्रतीक्षा करें...',
    loginSuccess: 'लॉगिन सफल',
    accountCreated: 'आपका खाता बन गया है!',
    error: 'त्रुटि',
    loginError: 'अमान्य ईमेल या पासवर्ड',
    registrationSuccess: 'पंजीकरण सफल',
    registrationError: 'पंजीकरण विफल। कृपया पुनः प्रयास करें।',
    demoCredentials: 'डेमो क्रेडेंशियल्स:',
    fetchingWeather: 'मौसम डेटा प्राप्त हो रहा है...',
    retry: 'पुनः प्रयास करें',
    forecast: '5-दिन का पूर्वानुमान',
    farmingRecommendations: 'AI खेती सिफारिशें',
    gettingRecommendations: 'सिफारिशें प्राप्त हो रही हैं...',
    noRecommendations: 'कोई सिफारिश उपलब्ध नहीं',
    failedToGetRecommendations: 'खेती सिफारिशें प्राप्त करने में विफल',
    logoutSuccess: 'लॉग आउट हो गया',
    logoutMessage: 'आप सफलतापूर्वक लॉग आउट हो गए हैं।',
  },
  te: {
    welcome: 'కిసాన్ మిత్రకు స్వాగతం',
    login: 'లాగిన్',
    register: 'నమోదు',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    name: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    location: 'స్థానం',
    cropType: 'పంట రకం',
    dashboard: 'డాష్‌బోర్డ్',
    weather: 'వాతావరణం',
    soilHealth: 'నేల ఆరోగ్యం',
    pestDetection: 'తెగులు గుర్తింపు',
    marketPrices: 'మార్కెట్ ధరలు',
    chatbot: 'కిసాన్ మిత్రను అడగండి',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్‌అవుట్',
    askQuestion: 'మీ ప్రశ్న అడగండి...',
    voiceInput: 'మాట్లాడటానికి నొక్కండి',
    uploadImage: 'చిత్రం అప్‌లోడ్',
    alerts: 'హెచ్చరికలు',
    recommendations: 'సిఫార్సులు',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    rainfall: 'వర్షపాతం',
    windSpeed: 'గాలి వేగం',
    soilPH: 'నేల pH',
    nitrogen: 'నత్రజని (N)',
    phosphorus: 'భాస్వరం (P)',
    potassium: 'పొటాషియం (K)',
    moisture: 'తేమ',
    analyze: 'విశ్లేషించు',
    loading: 'లోడ్ అవుతోంది...',
    submit: 'సమర్పించు',
    cancel: 'రద్దు',
    save: 'సేవ్',
    selectLanguage: 'భాష ఎంచుకోండి',
    greeting: 'నమస్కారం',
    howCanIHelp: 'ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    todayWeather: 'ఈరోజు వాతావరణం',
    marketUpdate: 'మార్కెట్ అప్‌డేట్',
    farmerLogin: 'రైతు లాగిన్',
    adminLogin: 'అడ్మిన్ లాగిన్',
    newFarmer: 'కొత్త రైతు? నమోదు చేయండి',
    existingUser: 'ఖాతా ఉందా? లాగిన్ చేయండి',
    welcomeBack: 'తిరిగి స్వాగతం',
    createAccount: 'ఖాతా సృష్టించండి',
    loginDescription: 'మీ పంట సలహాను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి',
    registerDescription: 'స్మార్ట్ వ్యవసాయం కోసం కృషి మిత్రలో చేరండి',
    fullName: 'పూర్తి పేరు',
    enterName: 'మీ పేరు నమోదు చేయండి',
    enterLocation: 'మీ గ్రామం/నగరం, రాష్ట్రం',
    preferredLanguage: 'ప్రాధాన్య భాష',
    enterCrops: 'వరి, గోధుమ, చెరకు...',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    noAccount: 'ఖాతా లేదా?',
    hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    pleaseWait: 'దయచేసి వేచి ఉండండి...',
    loginSuccess: 'లాగిన్ విజయవంతం',
    accountCreated: 'మీ ఖాతా సృష్టించబడింది!',
    error: 'లోపం',
    loginError: 'చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్',
    registrationSuccess: 'నమోదు విజయవంతం',
    registrationError: 'నమోదు విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    demoCredentials: 'డెమో ఆధారాలు:',
    fetchingWeather: 'వాతావరణ డేటా పొందుతోంది...',
    retry: 'మళ్ళీ ప్రయత్నించండి',
    forecast: '5-రోజుల సూచన',
    farmingRecommendations: 'AI వ్యవసాయ సిఫారసులు',
    gettingRecommendations: 'సిఫారసులు పొందుతోంది...',
    noRecommendations: 'సిఫారసులు అందుబాటులో లేవు',
    failedToGetRecommendations: 'వ్యవసాయ సిఫారసులు పొందడం విఫలమైంది',
    logoutSuccess: 'లాగ్ అవుట్ అయ్యారు',
    logoutMessage: 'మీరు విజయవంతంగా లాగ్ అవుట్ అయ్యారు.',
  },
  ta: {
    welcome: 'கிசான் மித்ராவுக்கு வரவேற்கிறோம்',
    login: 'உள்நுழைவு',
    register: 'பதிவு',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    name: 'முழு பெயர்',
    phone: 'தொலைபேசி எண்',
    location: 'இடம்',
    cropType: 'பயிர் வகை',
    dashboard: 'டாஷ்போர்டு',
    weather: 'வானிலை',
    soilHealth: 'மண் ஆரோக்கியம்',
    pestDetection: 'பூச்சி கண்டறிதல்',
    marketPrices: 'சந்தை விலைகள்',
    chatbot: 'கிசான் மித்ராவிடம் கேளுங்கள்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    askQuestion: 'உங்கள் கேள்வியைக் கேளுங்கள்...',
    voiceInput: 'பேச தட்டவும்',
    uploadImage: 'படம் பதிவேற்றம்',
    alerts: 'எச்சரிக்கைகள்',
    recommendations: 'பரிந்துரைகள்',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    rainfall: 'மழைப்பொழிவு',
    windSpeed: 'காற்று வேகம்',
    soilPH: 'மண் pH',
    nitrogen: 'நைட்ரஜன் (N)',
    phosphorus: 'பாஸ்பரஸ் (P)',
    potassium: 'பொட்டாசியம் (K)',
    moisture: 'ஈரப்பதம்',
    analyze: 'பகுப்பாய்வு',
    loading: 'ஏற்றுகிறது...',
    submit: 'சமர்ப்பி',
    cancel: 'ரத்து',
    save: 'சேமி',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    greeting: 'வணக்கம்',
    howCanIHelp: 'இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    todayWeather: 'இன்றைய வானிலை',
    marketUpdate: 'சந்தை புதுப்பிப்பு',
    farmerLogin: 'விவசாயி உள்நுழைவு',
    adminLogin: 'நிர்வாகி உள்நுழைவு',
    newFarmer: 'புதிய விவசாயி? பதிவு செய்யுங்கள்',
    existingUser: 'கணக்கு உள்ளதா? உள்நுழையவும்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    createAccount: 'கணக்கை உருவாக்கு',
    loginDescription: 'உங்கள் பயிர் ஆலோசனையை அணுக உள்நுழையவும்',
    registerDescription: 'ஸ்மார்ட் விவசாயத்திற்கு கிருஷி மித்ராவில் சேருங்கள்',
    fullName: 'முழு பெயர்',
    enterName: 'உங்கள் பெயரை உள்ளிடவும்',
    enterLocation: 'உங்கள் கிராமம்/நகரம், மாநிலம்',
    preferredLanguage: 'விருப்பமான மொழி',
    enterCrops: 'அரிசி, கோதுமை, கரும்பு...',
    signIn: 'உள்நுழை',
    signUp: 'பதிவு செய்',
    noAccount: 'கணக்கு இல்லையா?',
    hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    pleaseWait: 'தயவுசெய்து காத்திருங்கள்...',
    loginSuccess: 'உள்நுழைவு வெற்றி',
    accountCreated: 'உங்கள் கணக்கு உருவாக்கப்பட்டது!',
    error: 'பிழை',
    loginError: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்',
    registrationSuccess: 'பதிவு வெற்றி',
    registrationError: 'பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    demoCredentials: 'டெமோ சான்றுகள்:',
    fetchingWeather: 'வானிலை தரவு பெறப்படுகிறது...',
    retry: 'மீண்டும் முயற்சி',
    forecast: '5-நாள் கணிப்பு',
    farmingRecommendations: 'AI விவசாய பரிந்துரைகள்',
    gettingRecommendations: 'பரிந்துரைகள் பெறப்படுகின்றன...',
    noRecommendations: 'பரிந்துரைகள் இல்லை',
    failedToGetRecommendations: 'விவசாய பரிந்துரைகள் பெற முடியவில்லை',
    logoutSuccess: 'வெளியேறியது',
    logoutMessage: 'நீங்கள் வெற்றிகரமாக வெளியேறியுள்ளீர்கள்.',
  },
  kn: {
    welcome: 'ಕಿಸಾನ್ ಮಿತ್ರಕ್ಕೆ ಸ್ವಾಗತ',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    location: 'ಸ್ಥಳ',
    cropType: 'ಬೆಳೆ ಪ್ರಕಾರ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    weather: 'ಹವಾಮಾನ',
    soilHealth: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ',
    pestDetection: 'ಕೀಟ ಪತ್ತೆ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    chatbot: 'ಕಿಸಾನ್ ಮಿತ್ರನನ್ನು ಕೇಳಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    askQuestion: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    voiceInput: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    uploadImage: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    recommendations: 'ಶಿಫಾರಸುಗಳು',
    temperature: 'ತಾಪಮಾನ',
    humidity: 'ತೇವಾಂಶ',
    rainfall: 'ಮಳೆ',
    windSpeed: 'ಗಾಳಿ ವೇಗ',
    soilPH: 'ಮಣ್ಣಿನ pH',
    nitrogen: 'ನೈಟ್ರೋಜನ್ (N)',
    phosphorus: 'ಫಾಸ್ಫರಸ್ (P)',
    potassium: 'ಪೊಟ್ಯಾಸಿಯಂ (K)',
    moisture: 'ತೇವಾಂಶ',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    submit: 'ಸಲ್ಲಿಸಿ',
    cancel: 'ರದ್ದು',
    save: 'ಉಳಿಸಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    greeting: 'ನಮಸ್ಕಾರ',
    howCanIHelp: 'ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    todayWeather: 'ಇಂದಿನ ಹವಾಮಾನ',
    marketUpdate: 'ಮಾರುಕಟ್ಟೆ ಅಪ್‌ಡೇಟ್',
    farmerLogin: 'ರೈತ ಲಾಗಿನ್',
    adminLogin: 'ಅಡ್ಮಿನ್ ಲಾಗಿನ್',
    newFarmer: 'ಹೊಸ ರೈತ? ನೋಂದಣಿ ಮಾಡಿ',
    existingUser: 'ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    loginDescription: 'ನಿಮ್ಮ ಬೆಳೆ ಸಲಹೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    registerDescription: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿಗಾಗಿ ಕೃಷಿ ಮಿತ್ರದಲ್ಲಿ ಸೇರಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    enterName: 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    enterLocation: 'ನಿಮ್ಮ ಹಳ್ಳಿ/ನಗರ, ರಾಜ್ಯ',
    preferredLanguage: 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    enterCrops: 'ಅಕ್ಕಿ, ಗೋಧಿ, ಕಬ್ಬು...',
    signIn: 'ಸೈನ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    hasAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    pleaseWait: 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...',
    loginSuccess: 'ಲಾಗಿನ್ ಯಶಸ್ವಿ',
    accountCreated: 'ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!',
    error: 'ದೋಷ',
    loginError: 'ಅಮಾನ್ಯ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್',
    registrationSuccess: 'ನೋಂದಣಿ ಯಶಸ್ವಿ',
    registrationError: 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    demoCredentials: 'ಡೆಮೊ ರುಜುವಾತುಗಳು:',
    fetchingWeather: 'ಹವಾಮಾನ ಡೇಟಾ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    forecast: '5-ದಿನ ಮುನ್ಸೂಚನೆ',
    farmingRecommendations: 'AI ಕೃಷಿ ಶಿಫಾರಸುಗಳು',
    gettingRecommendations: 'ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    noRecommendations: 'ಶಿಫಾರಸುಗಳು ಲಭ್ಯವಿಲ್ಲ',
    failedToGetRecommendations: 'ಕೃಷಿ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ',
    logoutSuccess: 'ಲಾಗ್ ಔಟ್ ಆಗಿದ್ದೀರಿ',
    logoutMessage: 'ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್ ಔಟ್ ಆಗಿದ್ದೀರಿ.',
  },
  mr: {
    welcome: 'किसान मित्रामध्ये आपले स्वागत आहे',
    login: 'लॉगिन',
    register: 'नोंदणी',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूर्ण नाव',
    phone: 'फोन नंबर',
    location: 'स्थान',
    cropType: 'पीक प्रकार',
    dashboard: 'डॅशबोर्ड',
    weather: 'हवामान',
    soilHealth: 'मातीचे आरोग्य',
    pestDetection: 'कीड ओळख',
    marketPrices: 'बाजार भाव',
    chatbot: 'किसान मित्राला विचारा',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    askQuestion: 'तुमचा प्रश्न विचारा...',
    voiceInput: 'बोलण्यासाठी टॅप करा',
    uploadImage: 'फोटो अपलोड करा',
    alerts: 'सूचना',
    recommendations: 'शिफारसी',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'पाऊस',
    windSpeed: 'वाऱ्याची गती',
    soilPH: 'मातीचा pH',
    nitrogen: 'नायट्रोजन (N)',
    phosphorus: 'फॉस्फरस (P)',
    potassium: 'पोटॅश (K)',
    moisture: 'ओलावा',
    analyze: 'विश्लेषण करा',
    loading: 'लोड होत आहे...',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    save: 'सेव्ह करा',
    selectLanguage: 'भाषा निवडा',
    greeting: 'नमस्कार',
    howCanIHelp: 'आज मी तुम्हाला कशी मदत करू शकतो?',
    todayWeather: 'आजचे हवामान',
    marketUpdate: 'बाजार अपडेट',
    farmerLogin: 'शेतकरी लॉगिन',
    adminLogin: 'अॅडमिन लॉगिन',
    newFarmer: 'नवीन शेतकरी? नोंदणी करा',
    existingUser: 'खाते आहे? लॉगिन करा',
    welcomeBack: 'परत स्वागत',
    createAccount: 'खाते तयार करा',
    loginDescription: 'तुमच्या पीक सल्ल्यात प्रवेश करण्यासाठी साइन इन करा',
    registerDescription: 'स्मार्ट शेतीसाठी कृषी मित्रात सामील व्हा',
    fullName: 'पूर्ण नाव',
    enterName: 'तुमचे नाव टाका',
    enterLocation: 'तुमचे गाव/शहर, राज्य',
    preferredLanguage: 'पसंतीची भाषा',
    enterCrops: 'तांदूळ, गहू, ऊस...',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    noAccount: 'खाते नाही?',
    hasAccount: 'आधीच खाते आहे?',
    pleaseWait: 'कृपया प्रतीक्षा करा...',
    loginSuccess: 'लॉगिन यशस्वी',
    accountCreated: 'तुमचे खाते तयार झाले!',
    error: 'त्रुटी',
    loginError: 'अवैध ईमेल किंवा पासवर्ड',
    registrationSuccess: 'नोंदणी यशस्वी',
    registrationError: 'नोंदणी अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    demoCredentials: 'डेमो क्रेडेन्शियल्स:',
    fetchingWeather: 'हवामान डेटा मिळवत आहे...',
    retry: 'पुन्हा प्रयत्न करा',
    forecast: '5-दिवस अंदाज',
    farmingRecommendations: 'AI शेती शिफारसी',
    gettingRecommendations: 'शिफारसी मिळवत आहे...',
    noRecommendations: 'शिफारसी उपलब्ध नाहीत',
    failedToGetRecommendations: 'शेती शिफारसी मिळवण्यात अयशस्वी',
    logoutSuccess: 'लॉग आउट झाले',
    logoutMessage: 'तुम्ही यशस्वीरित्या लॉग आउट झालात.',
  },
  bn: {
    welcome: 'কিসান মিত্রায় স্বাগতম',
    login: 'লগইন',
    register: 'নিবন্ধন',
    email: 'ইমেল',
    password: 'পাসওয়ার্ড',
    name: 'পুরো নাম',
    phone: 'ফোন নম্বর',
    location: 'অবস্থান',
    cropType: 'ফসলের ধরন',
    dashboard: 'ড্যাশবোর্ড',
    weather: 'আবহাওয়া',
    soilHealth: 'মাটির স্বাস্থ্য',
    pestDetection: 'কীটপতঙ্গ সনাক্তকরণ',
    marketPrices: 'বাজার দর',
    chatbot: 'কিসান মিত্রাকে জিজ্ঞাসা করুন',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    askQuestion: 'আপনার প্রশ্ন জিজ্ঞাসা করুন...',
    voiceInput: 'কথা বলতে ট্যাপ করুন',
    uploadImage: 'ছবি আপলোড',
    alerts: 'সতর্কতা',
    recommendations: 'সুপারিশ',
    temperature: 'তাপমাত্রা',
    humidity: 'আর্দ্রতা',
    rainfall: 'বৃষ্টিপাত',
    windSpeed: 'বায়ুর গতি',
    soilPH: 'মাটির pH',
    nitrogen: 'নাইট্রোজেন (N)',
    phosphorus: 'ফসফরাস (P)',
    potassium: 'পটাসিয়াম (K)',
    moisture: 'আর্দ্রতা',
    analyze: 'বিশ্লেষণ',
    loading: 'লোড হচ্ছে...',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    greeting: 'নমস্কার',
    howCanIHelp: 'আজ আমি কীভাবে সাহায্য করতে পারি?',
    todayWeather: 'আজকের আবহাওয়া',
    marketUpdate: 'বাজার আপডেট',
    farmerLogin: 'কৃষক লগইন',
    adminLogin: 'অ্যাডমিন লগইন',
    newFarmer: 'নতুন কৃষক? নিবন্ধন করুন',
    existingUser: 'অ্যাকাউন্ট আছে? লগইন করুন',
    welcomeBack: 'ফিরে আসার স্বাগতম',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    loginDescription: 'আপনার ফসল পরামর্শ অ্যাক্সেস করতে সাইন ইন করুন',
    registerDescription: 'স্মার্ট কৃষির জন্য কৃষি মিত্রায় যোগ দিন',
    fullName: 'পুরো নাম',
    enterName: 'আপনার নাম লিখুন',
    enterLocation: 'আপনার গ্রাম/শহর, রাজ্য',
    preferredLanguage: 'পছন্দের ভাষা',
    enterCrops: 'ধান, গম, আখ...',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    noAccount: 'অ্যাকাউন্ট নেই?',
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    pleaseWait: 'অনুগ্রহ করে অপেক্ষা করুন...',
    loginSuccess: 'লগইন সফল',
    accountCreated: 'আপনার অ্যাকাউন্ট তৈরি হয়েছে!',
    error: 'ত্রুটি',
    loginError: 'অবৈধ ইমেল বা পাসওয়ার্ড',
    registrationSuccess: 'নিবন্ধন সফল',
    registrationError: 'নিবন্ধন ব্যর্থ। আবার চেষ্টা করুন।',
    demoCredentials: 'ডেমো শংসাপত্র:',
    fetchingWeather: 'আবহাওয়া ডেটা আনা হচ্ছে...',
    retry: 'আবার চেষ্টা',
    forecast: '5-দিনের পূর্বাভাস',
    farmingRecommendations: 'AI কৃষি সুপারিশ',
    gettingRecommendations: 'সুপারিশ পাওয়া যাচ্ছে...',
    noRecommendations: 'কোনো সুপারিশ নেই',
    failedToGetRecommendations: 'কৃষি সুপারিশ পেতে ব্যর্থ',
    logoutSuccess: 'লগ আউট হয়েছে',
    logoutMessage: 'আপনি সফলভাবে লগ আউট করেছেন।',
  },
  gu: {
    welcome: 'કિસાન મિત્રામાં આપનું સ્વાગત છે',
    login: 'લૉગિન',
    register: 'નોંધણી',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    name: 'પૂરું નામ',
    phone: 'ફોન નંબર',
    location: 'સ્થાન',
    cropType: 'પાક પ્રકાર',
    dashboard: 'ડેશબોર્ડ',
    weather: 'હવામાન',
    soilHealth: 'જમીન આરોગ્ય',
    pestDetection: 'જીવાત ઓળખ',
    marketPrices: 'બજાર ભાવ',
    chatbot: 'કિસાન મિત્રાને પૂછો',
    profile: 'પ્રોફાઇલ',
    logout: 'લૉગઆઉટ',
    askQuestion: 'તમારો પ્રશ્ન પૂછો...',
    voiceInput: 'બોલવા માટે ટેપ કરો',
    uploadImage: 'ફોટો અપલોડ',
    alerts: 'ચેતવણીઓ',
    recommendations: 'ભલામણો',
    temperature: 'તાપમાન',
    humidity: 'ભેજ',
    rainfall: 'વરસાદ',
    windSpeed: 'પવનની ઝડપ',
    soilPH: 'જમીનનું pH',
    nitrogen: 'નાઇટ્રોજન (N)',
    phosphorus: 'ફોસ્ફરસ (P)',
    potassium: 'પોટેશિયમ (K)',
    moisture: 'ભેજ',
    analyze: 'વિશ્લેષણ',
    loading: 'લોડ થઈ રહ્યું છે...',
    submit: 'સબમિટ',
    cancel: 'રદ કરો',
    save: 'સાચવો',
    selectLanguage: 'ભાષા પસંદ કરો',
    greeting: 'નમસ્તે',
    howCanIHelp: 'આજે હું તમને કેવી રીતે મદદ કરી શકું?',
    todayWeather: 'આજનું હવામાન',
    marketUpdate: 'બજાર અપડેટ',
    farmerLogin: 'ખેડૂત લૉગિન',
    adminLogin: 'એડમિન લૉગિન',
    newFarmer: 'નવા ખેડૂત? નોંધણી કરો',
    existingUser: 'ખાતું છે? લૉગિન કરો',
    welcomeBack: 'પાછા આવવાનું સ્વાગત',
    createAccount: 'ખાતું બનાવો',
    loginDescription: 'તમારી પાક સલાહ ઍક્સેસ કરવા સાઇન ઇન કરો',
    registerDescription: 'સ્માર્ટ ખેતી માટે કૃષિ મિત્રામાં જોડાઓ',
    fullName: 'પૂરું નામ',
    enterName: 'તમારું નામ દાખલ કરો',
    enterLocation: 'તમારું ગામ/શહેર, રાજ્ય',
    preferredLanguage: 'પસંદગીની ભાષા',
    enterCrops: 'ચોખા, ઘઉં, શેરડી...',
    signIn: 'સાઇન ઇન',
    signUp: 'સાઇન અપ',
    noAccount: 'ખાતું નથી?',
    hasAccount: 'પહેલેથી ખાતું છે?',
    pleaseWait: 'કૃપા કરી રાહ જુઓ...',
    loginSuccess: 'લૉગિન સફળ',
    accountCreated: 'તમારું ખાતું બનાવાયું!',
    error: 'ભૂલ',
    loginError: 'અમાન્ય ઇમેઇલ અથવા પાસવર્ડ',
    registrationSuccess: 'નોંધણી સફળ',
    registrationError: 'નોંધણી નિષ્ફળ. ફરી પ્રયાસ કરો.',
    demoCredentials: 'ડેમો ઓળખપત્રો:',
    fetchingWeather: 'હવામાન ડેટા મેળવી રહ્યા છે...',
    retry: 'ફરી પ્રયાસ',
    forecast: '5-દિવસ આગાહી',
    farmingRecommendations: 'AI ખેતી ભલામણો',
    gettingRecommendations: 'ભલામણો મેળવી રહ્યા છે...',
    noRecommendations: 'ભલામણો ઉપલબ્ધ નથી',
    failedToGetRecommendations: 'ખેતી ભલામણો મેળવવામાં નિષ્ફળ',
    logoutSuccess: 'લૉગ આઉટ થયા',
    logoutMessage: 'તમે સફળતાપૂર્વક લૉગ આઉટ થયા છો.',
  },
  pa: {
    welcome: 'ਕਿਸਾਨ ਮਿੱਤਰ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    login: 'ਲੌਗਇਨ',
    register: 'ਰਜਿਸਟਰ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    name: 'ਪੂਰਾ ਨਾਮ',
    phone: 'ਫ਼ੋਨ ਨੰਬਰ',
    location: 'ਸਥਾਨ',
    cropType: 'ਫ਼ਸਲ ਦੀ ਕਿਸਮ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    weather: 'ਮੌਸਮ',
    soilHealth: 'ਮਿੱਟੀ ਦੀ ਸਿਹਤ',
    pestDetection: 'ਕੀੜੇ ਦੀ ਪਛਾਣ',
    marketPrices: 'ਮੰਡੀ ਭਾਅ',
    chatbot: 'ਕਿਸਾਨ ਮਿੱਤਰ ਨੂੰ ਪੁੱਛੋ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    logout: 'ਲੌਗਆਊਟ',
    askQuestion: 'ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ...',
    voiceInput: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
    uploadImage: 'ਫੋਟੋ ਅੱਪਲੋਡ',
    alerts: 'ਚੇਤਾਵਨੀਆਂ',
    recommendations: 'ਸਿਫਾਰਸ਼ਾਂ',
    temperature: 'ਤਾਪਮਾਨ',
    humidity: 'ਨਮੀ',
    rainfall: 'ਬਾਰਿਸ਼',
    windSpeed: 'ਹਵਾ ਦੀ ਗਤੀ',
    soilPH: 'ਮਿੱਟੀ ਦਾ pH',
    nitrogen: 'ਨਾਈਟ੍ਰੋਜਨ (N)',
    phosphorus: 'ਫਾਸਫੋਰਸ (P)',
    potassium: 'ਪੋਟਾਸ਼ (K)',
    moisture: 'ਨਮੀ',
    analyze: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੇਵ ਕਰੋ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    greeting: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    howCanIHelp: 'ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
    todayWeather: 'ਅੱਜ ਦਾ ਮੌਸਮ',
    marketUpdate: 'ਮੰਡੀ ਅੱਪਡੇਟ',
    farmerLogin: 'ਕਿਸਾਨ ਲੌਗਇਨ',
    adminLogin: 'ਐਡਮਿਨ ਲੌਗਇਨ',
    newFarmer: 'ਨਵੇਂ ਕਿਸਾਨ? ਰਜਿਸਟਰ ਕਰੋ',
    existingUser: 'ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ',
    welcomeBack: 'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    loginDescription: 'ਆਪਣੀ ਫ਼ਸਲ ਸਲਾਹ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    registerDescription: 'ਸਮਾਰਟ ਖੇਤੀ ਲਈ ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ ਨਾਲ ਜੁੜੋ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    enterName: 'ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    enterLocation: 'ਤੁਹਾਡਾ ਪਿੰਡ/ਸ਼ਹਿਰ, ਰਾਜ',
    preferredLanguage: 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
    enterCrops: 'ਚੌਲ, ਕਣਕ, ਗੰਨਾ...',
    signIn: 'ਸਾਈਨ ਇਨ',
    signUp: 'ਸਾਈਨ ਅੱਪ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ?',
    hasAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    pleaseWait: 'ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...',
    loginSuccess: 'ਲੌਗਇਨ ਸਫਲ',
    accountCreated: 'ਤੁਹਾਡਾ ਖਾਤਾ ਬਣ ਗਿਆ!',
    error: 'ਗਲਤੀ',
    loginError: 'ਅਵੈਧ ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ',
    registrationSuccess: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ',
    registrationError: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    demoCredentials: 'ਡੈਮੋ ਪ੍ਰਮਾਣ ਪੱਤਰ:',
    fetchingWeather: 'ਮੌਸਮ ਡੇਟਾ ਲੈ ਰਿਹਾ ਹੈ...',
    retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼',
    forecast: '5-ਦਿਨ ਅਨੁਮਾਨ',
    farmingRecommendations: 'AI ਖੇਤੀ ਸਿਫਾਰਸ਼ਾਂ',
    gettingRecommendations: 'ਸਿਫਾਰਸ਼ਾਂ ਲੈ ਰਿਹਾ ਹੈ...',
    noRecommendations: 'ਕੋਈ ਸਿਫਾਰਸ਼ਾਂ ਉਪਲਬਧ ਨਹੀਂ',
    failedToGetRecommendations: 'ਖੇਤੀ ਸਿਫਾਰਸ਼ਾਂ ਲੈਣ ਵਿੱਚ ਅਸਫਲ',
    logoutSuccess: 'ਲੌਗ ਆਊਟ ਹੋ ਗਿਆ',
    logoutMessage: 'ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਲੌਗ ਆਊਟ ਹੋ ਗਏ ਹੋ।',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
